### ISSUE TITLE
Change GET api/v1/questions API

### ISSUE THREAD

**Issue by prasa-dd-vp** [Blackdeathanton/gatorexchange#26]
Currently, the following params are there in the GET [api/v1/questions](https://github.com/Blackdeathanton/gatorexchange/wiki/Backend#get-apiv1questions) API response,
* _id
* answers
* author
* body
* comments
* createdtime
* downvotes
* email
* tags
* title
* updatedtime
* upvotes
* views

Out of the which, answers and comments params are not necessary as it will not be needed anywhere in the questions list view.

**Comment by vikashpandian** [comment]
Api was changed as per the request
