### ISSUE TITLE
Develop an API to filter questions based on properties

### ISSUE THREAD

**Issue by Blackdeathanton** [Blackdeathanton/gatorexchange#52]
Develop an API to filter questions based on properties like score, or has answers

**Comment by vikashpandian** [comment]
Modified the existing GetQuestions apis to handle the filter parameters.

The filter parameters provided are HasUpvotes, NoAnswers
Multiple filters can be entered by seperating parameters with comma (,)

Eg: http://localhost:8000/api/v1/questions?filters=HasUpvotes,NoAnswers
