### ISSUE TITLE
Need to have a seperate API for handling upvote and downvote of answers

### ISSUE THREAD

**Issue by prasa-dd-vp** [Blackdeathanton/gatorexchange#57]
Currently we only have a POST API for upvote and downvote of questions. We need seperate POST API for voting for answers too.

**Comment by vikashpandian** [comment]
The url for the post request is of the format
<server_url>:<port>/api/v3/questions/:id/answers/:answer_id/vote/:vote

vote can have options: 
1. upvote
2. 2. downvote

Eg: http://127.0.0.1:8000/api/v3/questions/62420a636728f6b5d079e0b1/answers/62420e187f25db97e125b722/vote/upvote
