### ISSUE TITLE
Design and develop an API to delete a comment 

### ISSUE THREAD

**Issue by Blackdeathanton** [Blackdeathanton/gatorexchange#98]
Design and develop an API to delete a comment

**Comment by vikashpandian** [comment]
https://github.com/Blackdeathanton/gatorexchange/commit/b54b6f8d33ba0ec43a784a9392491f513b723db1

**Comment by vikashpandian** [comment]
https://github.com/Blackdeathanton/gatorexchange/commit/17218a5d08c3e774c38bcddc79552103255ec1c5
